xlam_fc:
  resources_servers:
    xlam_fc:
      entrypoint: app.py
      domain: agent
      verified: false
xlam_fc_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: xlam_fc
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/xlam_fc/data/example.jsonl
      - name: train
        type: train
        jsonl_fpath: resources_servers/xlam_fc/data/train.jsonl
        gitlab_identifier:
          dataset_name: xlam_function_calling_60k
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: valid
        type: validation
        jsonl_fpath: resources_servers/xlam_fc/data/valid.jsonl
        gitlab_identifier:
          dataset_name: xlam_function_calling_60k
          version: 0.0.1
          artifact_fpath: valid.jsonl
        license: Apache 2.0
